### ISSUE TITLE
Change Password link is not working

### ISSUE THREAD

**Issue by schrattenholz** [symbiote/silverstripe-memberprofiles#163] opened 2019-07-25 08:14 UTC
If logged in instead of password fields there is only shown a "Change Password" -Link. But it has no functionaltiy... Any advice?

**Comment by nglasl** [comment] 2019-10-01 07:04
https://github.com/symbiote/silverstripe-memberprofiles/pull/153 has now been merged which I believe resolves an issue with the change password not working, can you please give this another test to confirm?

**Comment by EEKimS** [comment] 2019-12-27 18:39
I can confirm that this is not fixed, there is no jquery on the memberprofiles page and the "Change password" link does nothing.

Also you cannot save the profile without the password field being provided? I can see an option to make this field not required, but it seems odd that it would be an issue.

**Comment by EEKimS** [comment] 2019-12-27 18:50
also manually adding jquery manually doesn't seem to fix this either, i have it loaded and working but the Change Password still doesn't seem to do anything.

**Comment by nglasl** [comment] 2020-06-02 06:50
Sorry I never got a notification for this. I'm having a play with this now for you and it's definitely working from what I can see. However there may be something else at play such as https://github.com/symbiote/silverstripe-memberprofiles/issues/166 that's project specific. You may need to check your browser console to see what errors might be happening.

In regards to the password field always being required, I agree that it's not ideal when you haven't selected to change password. I'm all for changing this, but having a quick dig there's a bunch of logic specifically around the password that makes this a little complicated. I'm assuming it's also required for the registration page, as opposed to just the profile page when logged in. If someone has a bit more time to spend on this, I'd be more than happy to review a PR.

**Comment by DigNZ** [comment] 2021-08-02 20:46
A year late to the party, I'm having the same error and I think its because of bootstrap. The container has class 'd-none' but the jquery toggle doesn't toggle that so bootstrap keeps it hidden. Obviously if the site isn't using bootstrap then the d-none class doesn't hide anything and the system works fine.

**Closed** 2022-11-27 21:56 UTC
Labels: affects/v4, effort/medium
